#!/bin/bash

root_dev=`grep -oPr "root=[^\s]*" /boot/cmdline.txt | awk -F= '{printf $NF}'`
version=`uname -v`
version=${version##* }

if [ -f /etc/X11/xorg.conf.d/40-libinput.conf ]; then
sudo rm -rf /etc/X11/xorg.conf.d/40-libinput.conf
fi
if [ ! -d /etc/X11/xorg.conf.d ]; then
sudo mkdir -p /etc/X11/xorg.conf.d
fi
sudo cp ./overlays/tft35a-overlay.dtb /boot/overlays/
sudo cp ./overlays/tft35a-overlay.dtb /boot/overlays/tft35a.dtbo
sudo cp -rf ./boot/config-35.txt /boot/config.txt
sudo cp -rf ./config/99-calibration.conf-35  /etc/X11/xorg.conf.d/99-calibration.conf
sudo cp -rf ./config/99-fbturbo.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
if test "$root_dev" = "/dev/mmcblk0p7";then
sudo cp ./boot/cmdline.txt-noobs /boot/cmdline.txt
else
sudo cp ./boot/cmdline.txt /boot/
fi
sudo cp ./etc/inittab /etc/

#evdev install
echo $version
if test $version -lt 2017;then
echo "reboot"
else
echo "need to update touch configuration"
sudo apt-get install xserver-xorg-input-evdev -y 2> error.txt
result=`cat ./error.txt`
echo -e "\033[31m$result\033[0m"
grep -q "^E:" ./error.txt && exit
sudo cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf
#echo "reboot"
fi
#else
#echo "this is not raspberrypi kernel, no need to update touch configure, reboot"
#fi

echo "reboot now"
sudo reboot
